<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * CodeIgniter Application Configuration File
 * 
 * Sistem Penjadwalan Guru SMK Berbasis Algoritma Genetika
 * Versi: 1.0.0
 * 
 * Referensi SRS: Bab 11.10 (PDF Engine), Bab 16.3 (CSRF), Bab 12 (Feedback)
 */

// ------------------------------------------------------------------
// GENERAL APPLICATION SETTINGS
// ------------------------------------------------------------------

/*
 |--------------------------------------------------------------------------
 | Base Site URL
 |--------------------------------------------------------------------------
 |
 | URL to your CodeIgniter root. Typically this will be your base URL,
 | WITH a trailing slash:
 |
 |	http://example.com/
 |
 | WARNING: You MUST set this value!
 |
 | If it is not set, then CodeIgniter will try guess the protocol and path
 | your installation resides on.
 |
 | Please check you have a www. in there for production websites without
 | redirecting from non-www to www or vice versa. For example:
 |
 |   $config['base_url'] = 'http://www.example.com/';
 |   $config['base_url'] = 'https://www.example.com/';
 |   $config['base_url'] = 'http://localhost/myproject/';
 |
 | It's also recommended to set the $config['index_page'] if you're using
 | index.php in your URLs.
 |
 |   $config['index_page'] = 'index.php';
 |
 */
$config['base_url'] = 'http://localhost/scheduling-system/';

/*
 |--------------------------------------------------------------------------
 | Index File
 |--------------------------------------------------------------------------
 |
 | Typically this will be your index.php file, unless you've renamed it to
 | something else. If you are using mod_rewrite to remove the page set this
 | variable so that it is blank.
 |
 */
$config['index_page'] = '';

/*
 |--------------------------------------------------------------------------
 | URI PROTOCOL
 |--------------------------------------------------------------------------
 |
 | This item determines which server global should be used to retrieve the
 | URI string. The default setting of 'REQUEST_URI' works for most servers.
 | If your links do not seem to work, try one of the other delicious flavors:
 |
 | 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
 | 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
 | 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
 |
 | WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
 */
$config['uri_protocol'] = 'REQUEST_URI';

/*
 |--------------------------------------------------------------------------
 | URL suffix
 |--------------------------------------------------------------------------
 |
 | This option allows you to add a suffix to all URLs generated by CodeIgniter.
 | For more information please see the user guide:
 |
 | https://codeigniter.com/userguide3/general/urls.html
 |
 | Note: This option is ignored for CLI requests.
 |
 | Example: '.html'
 */
$config['url_suffix'] = '';

/*
 |--------------------------------------------------------------------------
 | Default Language
 |--------------------------------------------------------------------------
 |
 | This determines which set of language files should be used. Make sure
 | there is an available translation if you intend to use something other
 | than english.
 |
 */
$config['language'] = 'indonesian';

/*
 |--------------------------------------------------------------------------
 | Default Character Set
 |--------------------------------------------------------------------------
 |
 | This determines which character set is used by default in various methods
 | that require a character set to be provided.
 |
 | See http://php.net/htmlspecialchars for a list of supported charsets.
 |
 */
$config['charset'] = 'UTF-8';

/*
 |--------------------------------------------------------------------------
 | Enable/Disable System Hooks
 |--------------------------------------------------------------------------
 |
 | If you would like to use the 'hooks' feature you must enable it by
 | setting this variable to TRUE (boolean). See the user guide for details.
 |
 */
$config['enable_hooks'] = TRUE;

/*
 |--------------------------------------------------------------------------
 | Class Extension Prefix
 |--------------------------------------------------------------------------
 |
 | This item allows you to set the filename/classname prefix when extending
 | native libraries. For more information please see the user guide:
 |
 | https://codeigniter.com/userguide3/general/core_classes.html
 | https://codeigniter.com/userguide3/general/creating_libraries.html
 |
 */
$config['subclass_prefix'] = 'MY_';

/*
 |--------------------------------------------------------------------------
 | Composer auto-loading
 |--------------------------------------------------------------------------
 |
 | Enabling this setting will tell CodeIgniter to look for a Composer
 | package auto-loader script in application/vendor/autoload.php.
 |
 |	$config['composer_autoload'] = TRUE;
 |
 | Or if you have your vendor/ directory located somewhere else, you
 | can opt to set a specific path as well:
 |
 |	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
 |
 | For more information about Composer, please visit http://getcomposer.org/
 |
 | Note: This will NOT disable or override the CodeIgniter-specific
 |	autoloading (application/config/autoload.php)
 */
$config['composer_autoload'] = APPPATH . 'vendor/autoload.php';

/*
 |--------------------------------------------------------------------------
 | Allowed URL Characters
 |--------------------------------------------------------------------------
 |
 | This lets you specify which characters are permitted within your URLs.
 | When someone tries to submit a URL with disallowed characters they will
 | get a warning message.
 |
 | As a security measure you are STRONGLY encouraged to restrict URLs to
 | as few characters as possible. By default only these are allowed: a-z 0-9~%.:_-
 |
 | Set to an empty string to allow all characters -- but only if you are insane.
 |
 | The configured value is actually a regular expression character group
 | and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
 |
 | DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
 |
 */
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
 |--------------------------------------------------------------------------
 | Enable Query Strings
 |--------------------------------------------------------------------------
 |
 | By default CodeIgniter uses search-engine friendly segment based URLs:
 | example.com/who/what/where/
 |
 | You can optionally enable standard query string based URLs:
 | example.com?who=me&what=something&where=here
 |
 | Options are: TRUE or FALSE (boolean)
 |
 | The other items let you set the query string 'words' that will
 | invoke your controllers and its functions:
 | example.com/index.php?c=controller&m=function&s[additional]=param
 |
 | Please note that some of the helpers won't work as expected when
 | this feature is enabled, since CodeIgniter is designed primarily to
 | use segment based URLs.
 |
 */
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
 |--------------------------------------------------------------------------
 | Allow $_GET array
 |--------------------------------------------------------------------------
 |
 | By default CodeIgniter enables search-engine friendly segment based URLs:
 | example.com/who/what/where/
 |
 | However, you can optionally enable standard query string based URLs:
 | example.com?who=me&what=something&where=here
 |
 | Options are: TRUE or FALSE (boolean)
 |
 | The default value is TRUE if enable_query_strings is TRUE, FALSE otherwise.
 |
 */
$config['allow_get_array'] = TRUE;

// ------------------------------------------------------------------
// ERROR REPORTING & LOGGING (Production Settings)
// ------------------------------------------------------------------

/*
 |--------------------------------------------------------------------------
 | Error Logging Threshold
 |--------------------------------------------------------------------------
 |
 | Setting untuk production environment:
 | - 0 = Disable logging
 | - 1 = Error Messages (Errors, PHP Errors)
 | - 2 = Debug Messages
 | - 3 = Informational Messages
 | - 4 = All Messages
 |
 | Untuk production: set ke 1 (hanya error penting yang dicatat)
 | Stack trace tidak ditampilkan ke user (lihat views/errors/)
 */
$config['log_threshold'] = 1;

/*
 |--------------------------------------------------------------------------
 | Error Logging Path
 |--------------------------------------------------------------------------
 */
$config['log_path'] = APPPATH . 'logs/';

/*
 |--------------------------------------------------------------------------
 | Log File Extension
 |--------------------------------------------------------------------------
 */
$config['log_file_extension'] = '';

/*
 |--------------------------------------------------------------------------
 | Log File Permissions
 |--------------------------------------------------------------------------
 */
$config['log_file_permissions'] = 0644;

/*
 |--------------------------------------------------------------------------
 | Date Format for Logs
 |--------------------------------------------------------------------------
 */
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
 |--------------------------------------------------------------------------
 | Error Views Directory
 |--------------------------------------------------------------------------
 | Custom error pages telah dibuat di application/views/errors/
 | - 403.php: Akses Ditolak
 | - 404.php: Halaman Tidak Ditemukan
 | - 500.php: Terjadi Kesalahan Server
 */
$config['error_views_path'] = APPPATH . 'views/errors/';

/*
 |--------------------------------------------------------------------------
 | Cache Directory Path
 |--------------------------------------------------------------------------
 */
$config['cache_path'] = '';

/*
 |--------------------------------------------------------------------------
 | Encryption Key
 |--------------------------------------------------------------------------
 |
 | If you use the Encryption class, you must set an encryption key.
 | See the user guide for more info.
 |
 | https://codeigniter.com/userguide3/libraries/encryption.html
 |
 */
$config['encryption_key'] = 'YourSecretKeyHere_ChangeThisInProduction_32CharsMinimum!';

// ------------------------------------------------------------------
// SESSION CONFIGURATION
// ------------------------------------------------------------------

/*
 |--------------------------------------------------------------------------
 | Session Variables
 |--------------------------------------------------------------------------
 |
 | 'sess_driver'
 |
 |	The storage driver to use: files, database, redis, memcached
 |
 | 'sess_cookie_name'
 |
 |	The session cookie name, must contain only [0-9a-z_-] characters
 |
 | 'sess_expiration'
 |
 |	The number of SECONDS you want the session to last.
 |	Setting to 0 (zero) means expire when the browser is closed.
 |
 | 'sess_save_path'
 |
 |	The location to save sessions to, driver dependent.
 |
 |	For the 'files' driver, it's a path to a writable directory.
 |	WARNING: Only absolute paths are supported!
 |
 |	For the 'database' driver, it's a table name.
 |	Please read up the manual for the format with other session drivers.
 |
 |	IMPORTANT: You are REQUIRED to set a valid save path for 'files' and 'database' drivers.
 |
 | 'sess_match_ip'
 |
 |	Whether to match the user's IP address when reading the session data.
 |
 |	WARNING: If you're using the database driver, don't forget to update
 |	         your session table's PRIMARY KEY when changing this setting.
 |
 | 'sess_time_to_update'
 |
 |	How many seconds between CI regenerating the session ID.
 |
 | 'sess_regenerate_destroy'
 |
 |	Whether to destroy session data associated with the old session ID
 |	when auto-regenerating the session ID. When set to FALSE, the data
 |	will be later deleted by the garbage collector.
 |
 | Other session cookie settings are shared with the rest of the application,
 | except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
 |
 */
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session_scheduling';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = APPPATH . 'sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

// ------------------------------------------------------------------
// COOKIE CONFIGURATION
// ------------------------------------------------------------------

/*
 |--------------------------------------------------------------------------
 | Cookie Related Variables
 |--------------------------------------------------------------------------
 |
 | 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
 | 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
 | 'cookie_path'     = Typically will be a forward slash
 | 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
 | 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
 |
 | Note: These settings (with the exception of 'cookie_prefix' and
 |       'cookie_httponly') will also affect sessions.
 |
 */
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;

// ------------------------------------------------------------------
// SECURITY SETTINGS (SRS Bab 16.3 - CSRF Protection)
// ------------------------------------------------------------------

/*
 |--------------------------------------------------------------------------
 | Cross Site Request Forgery
 |--------------------------------------------------------------------------
 | Enables a CSRF cookie token to be set. When set to TRUE, token will be
 | checked on a submitted form. If you are accepting user data, it is strongly
 | recommended CSRF protection be enabled.
 |
 | 'csrf_token_name' = The token name
 | 'csrf_cookie_name' = The cookie name
 | 'csrf_expire' = The number in seconds the token should expire.
 | 'csrf_regenerate' = Regenerate token on every submission
 | 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
 |
 | PENTING: Nama token harus sesuai dengan meta tag di main.php dan app.js
 |
 */
$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'csrf_token_name';
$config['csrf_cookie_name'] = 'csrf_token_hash';
$config['csrf_expire'] = 7200; // 2 jam
$config['csrf_regenerate'] = TRUE; // Regenerate setiap POST
$config['csrf_exclude_uris'] = []; // Tidak ada URI yang dikecualikan

/*
 |--------------------------------------------------------------------------
 | Global XSS Filtering
 |--------------------------------------------------------------------------
 */
$config['global_xss_filtering'] = FALSE;

/*
 |--------------------------------------------------------------------------
 | Standardize newlines
 |--------------------------------------------------------------------------
 */
$config['standardize_newlines'] = FALSE;

// ------------------------------------------------------------------
// OUTPUT & PERFORMANCE
// ------------------------------------------------------------------

/*
 |--------------------------------------------------------------------------
 | Output Compression
 |--------------------------------------------------------------------------
 */
$config['compress_output'] = FALSE;

/*
 |--------------------------------------------------------------------------
 | Cache Include Query String
 |--------------------------------------------------------------------------
 */
$config['cache_query_string'] = FALSE;

/*
 |--------------------------------------------------------------------------
 | Master Time Reference
 |--------------------------------------------------------------------------
 */
$config['time_reference'] = 'local';

/*
 |--------------------------------------------------------------------------
 | Rewrite PHP Short Tags
 |--------------------------------------------------------------------------
 */
$config['rewrite_short_tags'] = FALSE;

/*
 |--------------------------------------------------------------------------
 | Reverse Proxy IPs
 |--------------------------------------------------------------------------
 */
$config['proxy_ips'] = '';

// ------------------------------------------------------------------
// DOMPDF CONFIGURATION (Bab 11.10 - PDF Engine)
// ------------------------------------------------------------------

/*
 |--------------------------------------------------------------------------
 | Dompdf Options
 |--------------------------------------------------------------------------
 | Konfigurasi untuk Dompdf 1.x
 */
$config['dompdf_options'] = [
    'isRemoteEnabled' => TRUE,      // Izinkan load CSS/image dari URL
    'defaultFont'     => 'Arial',   // Font default untuk PDF
    'defaultPaperSize'=> 'A4',
    'defaultMediaType'=> 'screen',
    'isHtml5ParserEnabled' => TRUE, // Parse HTML5
    'isPhpEnabled'    => FALSE,     // Disable PHP di PDF (security)
];

// ------------------------------------------------------------------
// GA ALGORITHM CONFIGURATION
// ------------------------------------------------------------------

/*
 |--------------------------------------------------------------------------
 | Genetic Algorithm Parameters
 |--------------------------------------------------------------------------
 | Default parameters untuk Algoritma Genetika penjadwalan
 | Sesuai dengan SRS Bab 16.5
 */
$config['ga_population_size'] = 100;
$config['ga_max_generations'] = 500;
$config['ga_mutation_rate'] = 0.1;
$config['ga_crossover_rate'] = 0.8;
$config['ga_elite_count'] = 10;
$config['ga_tournament_size'] = 5;
$config['ga_timeout_seconds'] = 300; // 5 menit max execution

// ------------------------------------------------------------------
// APPLICATION SPECIFIC SETTINGS
// ------------------------------------------------------------------

/*
 |--------------------------------------------------------------------------
 | Application Info
 |--------------------------------------------------------------------------
 */
$config['app_name'] = 'Sistem Penjadwalan Guru SMK';
$config['app_version'] = '1.0.0';

/*
 |--------------------------------------------------------------------------
 | Pagination & Upload Settings
 |--------------------------------------------------------------------------
 */
$config['items_per_page'] = 10;
$config['max_upload_size_kb'] = 2048; // 2MB
$config['allowed_file_types'] = 'xls|xlsx|csv';

/*
 |--------------------------------------------------------------------------
 | Generate Schedule Settings
 |--------------------------------------------------------------------------
 | Konfigurasi untuk modul generate jadwal
 */
$config['generate_polling_interval'] = 2000; // 2 detik
$config['generate_redirect_delay'] = 3000; // 3 detik setelah sukses
$config['generate_review_url'] = 'waka/jadwal';

// ------------------------------------------------------------------
// END OF CONFIGURATION FILE
// ------------------------------------------------------------------
